
# By default, SwiftLint uses a set of sensible default rules you can adjust:

disabled_rules: # rule identifiers turned on by default to exclude from running
#  - cyclomatic_complexity
#  - function_parameter_count
#  - line_length
#  - identifier_name
#  - type_name
#  - force_cast
#  - function_body_length
#  - file_length
#  - type_body_length
#  - force_try
#  - shorthand_operator
#  - redundant_string_enum_value
#  - orphaned_doc_comment
#  - large_tuple
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - /LunchONTests 
  - /LunchONUITests 
  - /MUNCH\:ONTests  
  - /MUNCH\:ONUITests 
